import { useState, useMemo } from "react";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  DollarSign, Download, FileText, Calendar, TrendingUp,
  Heart, Shield, Activity, Stethoscope, Dumbbell, Gift,
  CheckCircle2, Clock, AlertCircle, Eye, Building2, Loader2,
} from "lucide-react";
import { toast } from "sonner";

const PLAN_TYPES: Record<string, { icon: any; color: string }> = {
  health: { icon: Stethoscope, color: "text-red-500 bg-red-50" },
  dental: { icon: Activity, color: "text-blue-500 bg-blue-50" },
  vision: { icon: Eye, color: "text-indigo-500 bg-indigo-50" },
  life: { icon: Shield, color: "text-emerald-500 bg-emerald-50" },
  retirement: { icon: Building2, color: "text-amber-500 bg-amber-50" },
  wellness: { icon: Dumbbell, color: "text-teal-500 bg-teal-50" },
  other: { icon: Gift, color: "text-violet-500 bg-violet-50" },
};

export default function EmployeePayrollBenefitsPage() {
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState<"payslips" | "benefits" | "compensation">("payslips");

  // Live data from backend
  const { data: payrollRecords = [], isLoading: loadingPayroll } = trpc.payroll.list.useQuery();
  const { data: payslips = [], isLoading: loadingPayslips } = trpc.payslip.myPayslips.useQuery();
  const { data: benefitPlans = [], isLoading: loadingPlans } = trpc.benefits.listPlans.useQuery();
  const { data: enrollments = [], isLoading: loadingEnrollments } = trpc.benefits.listEnrollments.useQuery();
  const { data: compensationRecords = [], isLoading: loadingComp } = trpc.compensation.list.useQuery();
  const { data: employees = [] } = trpc.employee.list.useQuery();

  // Find current employee record
  const myEmployee = useMemo(() => {
    if (!user) return null;
    return employees.find((e: any) => e.email === user.email || e.userId === user.id) || null;
  }, [employees, user]);

  const salary = myEmployee ? Number(myEmployee.salary) || 0 : 0;

  // Payslips for current employee (generated by admin)
  const myPayslips = useMemo(() => {
    if (!myEmployee) return payslips;
    return payslips;
  }, [payslips, myEmployee]);

  // Get latest payslip
  const latestPayslip = myPayslips.length > 0 ? myPayslips[0] : null;
  const lastNetPay = latestPayslip ? Number(latestPayslip.netPay || latestPayslip.grossSalary) || 0 : Math.round(salary / 12 * 0.75);

  // My enrollments with plan details
  const myBenefits = useMemo(() => {
    const myEnrollments = myEmployee
      ? enrollments.filter((e: any) => e.employeeId === myEmployee.id)
      : enrollments;

    return benefitPlans.map((plan: any) => {
      const enrollment = myEnrollments.find((e: any) => e.planId === plan.id);
      const cost = Number(plan.cost) || 0;
      const employerContrib = Number(plan.employerContribution) || 0;
      return {
        id: plan.id,
        type: plan.type || "other",
        name: plan.name,
        provider: plan.provider || "—",
        monthlyCost: cost,
        employerPays: employerContrib,
        youPay: Math.max(0, cost - employerContrib),
        enrolled: !!enrollment,
        enrollmentStatus: enrollment?.status || null,
      };
    });
  }, [benefitPlans, enrollments, myEmployee]);

  const totalYouPay = myBenefits.filter(b => b.enrolled).reduce((s, b) => s + b.youPay, 0);
  const totalEmployerPays = myBenefits.filter(b => b.enrolled).reduce((s, b) => s + b.employerPays, 0);

  // Compensation records for current employee
  const myCompRecords = useMemo(() => {
    if (!myEmployee) return compensationRecords;
    return compensationRecords.filter((c: any) => c.employeeId === myEmployee.id);
  }, [compensationRecords, myEmployee]);

  const bonusTotal = myCompRecords.filter((c: any) => c.type === "bonus").reduce((s: number, c: any) => s + (Number(c.amount) || 0), 0);
  const equityTotal = myCompRecords.filter((c: any) => c.type === "equity").reduce((s: number, c: any) => s + (Number(c.amount) || 0), 0);
  const benefitsValue = totalEmployerPays * 12;
  const totalComp = salary + bonusTotal + equityTotal + benefitsValue;

  const isLoading = loadingPayroll || loadingPlans || loadingEnrollments || loadingComp;

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="animate-spin text-teal-600" size={32} />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-slate-900">My Pay & Benefits</h1>
        <p className="text-sm text-slate-500 mt-1">View your payslips, benefits enrollment, and compensation details</p>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card className="border-0 shadow-sm">
          <CardContent className="p-5">
            <div className="w-10 h-10 rounded-xl bg-teal-50 flex items-center justify-center mb-2">
              <DollarSign size={20} className="text-teal-600" />
            </div>
            <p className="text-2xl font-bold text-slate-900">${lastNetPay.toLocaleString()}</p>
            <p className="text-xs text-slate-500 mt-1">Last Net Pay</p>
          </CardContent>
        </Card>
        <Card className="border-0 shadow-sm">
          <CardContent className="p-5">
            <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center mb-2">
              <Calendar size={20} className="text-blue-600" />
            </div>
            <p className="text-2xl font-bold text-slate-900">
              {myPayslips.length > 0 ? `${myPayslips.length} slips` : "—"}
            </p>
            <p className="text-xs text-slate-500 mt-1">Payslip Records</p>
          </CardContent>
        </Card>
        <Card className="border-0 shadow-sm">
          <CardContent className="p-5">
            <div className="w-10 h-10 rounded-xl bg-rose-50 flex items-center justify-center mb-2">
              <Heart size={20} className="text-rose-500" />
            </div>
            <p className="text-2xl font-bold text-slate-900">{myBenefits.filter(b => b.enrolled).length}</p>
            <p className="text-xs text-slate-500 mt-1">Active Benefits</p>
          </CardContent>
        </Card>
        <Card className="border-0 shadow-sm">
          <CardContent className="p-5">
            <div className="w-10 h-10 rounded-xl bg-emerald-50 flex items-center justify-center mb-2">
              <TrendingUp size={20} className="text-emerald-600" />
            </div>
            <p className="text-2xl font-bold text-slate-900">${totalEmployerPays.toLocaleString()}/mo</p>
            <p className="text-xs text-slate-500 mt-1">Employer Benefits Value</p>
          </CardContent>
        </Card>
      </div>

      {/* Tab Navigation */}
      <div className="flex gap-1 bg-slate-100 p-1 rounded-lg w-fit">
        {(["payslips", "benefits", "compensation"] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`px-4 py-2 rounded-md text-sm font-medium transition-colors capitalize ${
              activeTab === tab ? "bg-white text-slate-900 shadow-sm" : "text-slate-500 hover:text-slate-700"
            }`}
          >
            {tab === "payslips" ? "Payslips" : tab === "benefits" ? "My Benefits" : "Compensation"}
          </button>
        ))}
      </div>

      {/* Payslips Tab — Live from payroll records */}
      {activeTab === "payslips" && (
        <Card className="border-0 shadow-sm">
          <CardContent className="p-0">
            <div className="px-5 py-4 border-b border-slate-100 flex items-center justify-between">
              <div>
                <h3 className="font-semibold text-slate-900">Payslip History</h3>
                <p className="text-xs text-slate-500 mt-0.5">{myPayslips.length} records from database</p>
              </div>
              <Button variant="outline" size="sm" onClick={() => toast.info("Download all coming soon")}>
                <Download size={14} className="mr-1" />Download All
              </Button>
            </div>
            {myPayslips.length === 0 ? (
              <div className="py-12 text-center text-slate-400">
                <FileText size={40} className="mx-auto mb-3 text-slate-300" />
                <p className="text-sm font-medium">No payslip records yet</p>
                <p className="text-xs mt-1">Payslips will appear here after payroll cycles are processed</p>
              </div>
            ) : (
              <table className="w-full">
                <thead>
                  <tr className="bg-slate-50 text-xs font-semibold text-slate-500 uppercase tracking-wider">
                    <th className="px-5 py-3 text-left">Period</th>
                    <th className="px-5 py-3 text-right">Gross Pay</th>
                    <th className="px-5 py-3 text-right">Deductions</th>
                    <th className="px-5 py-3 text-right">Net Pay</th>
                    <th className="px-5 py-3 text-left">Status</th>
                    <th className="px-5 py-3 text-center">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {myPayslips.map((p: any) => {
                    const period = p.month ? `${new Date(p.year, p.month - 1).toLocaleString(undefined, { month: 'long', year: 'numeric' })}` : (p.createdAt ? new Date(p.createdAt).toLocaleDateString() : "—");
                    const net = Number(p.netPay || p.grossSalary || 0);
                    return (
                      <tr key={p.id} className="hover:bg-slate-50/50 transition-colors">
                        <td className="px-5 py-3">
                          <p className="text-sm font-medium text-slate-900">{period}</p>
                          <p className="text-xs text-slate-500">{p.availabilityDate ? new Date(p.availabilityDate).toLocaleDateString() : (p.sentAt ? new Date(p.sentAt).toLocaleDateString() : "—")}</p>
                        </td>
                        <td className="px-5 py-3 text-sm text-slate-900 text-right">{p.currency} {net.toLocaleString()}</td>
                        <td className="px-5 py-3 text-sm text-red-500 text-right">-{p.currency} {Number(p.aTax || 0).toLocaleString()}</td>
                        <td className="px-5 py-3 text-sm text-slate-900 text-right font-bold">{p.currency} {net.toLocaleString()}</td>
                        <td className="px-5 py-3">
                          <Badge variant="outline" className={`text-xs border-0 capitalize ${
                            p.status === "sent" ? "bg-emerald-50 text-emerald-700" :
                            p.status === "validated" ? "bg-amber-50 text-amber-700" :
                            "bg-slate-50 text-slate-600"
                          }`}>{p.status || "processed"}</Badge>
                        </td>
                        <td className="px-5 py-3 text-center">
                          {p.pdfUrl ? (
                            <a href={p.pdfUrl} target="_blank" rel="noreferrer">
                              <Button variant="ghost" size="sm" className="h-7"><Download size={14} className="mr-1" />PDF</Button>
                            </a>
                          ) : (
                            <Button variant="ghost" size="sm" className="h-7" onClick={() => toast.info("PDF not available yet")}> <Download size={14} className="mr-1" />PDF</Button>
                          )}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            )}
          </CardContent>
        </Card>
      )}

      {/* Benefits Tab — Live from benefit plans and enrollments */}
      {activeTab === "benefits" && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-slate-600">Your monthly contribution: <span className="font-bold text-slate-900">${totalYouPay.toLocaleString()}</span></p>
              <p className="text-xs text-slate-500">Employer contribution: ${totalEmployerPays.toLocaleString()}/month</p>
            </div>
            <Button variant="outline" size="sm" onClick={() => toast.info("Open enrollment coming soon")}>
              Open Enrollment
            </Button>
          </div>

          {myBenefits.length === 0 ? (
            <Card className="border-0 shadow-sm">
              <CardContent className="py-12 text-center text-slate-400">
                <Heart size={40} className="mx-auto mb-3 text-slate-300" />
                <p className="text-sm font-medium">No benefit plans available</p>
                <p className="text-xs mt-1">Contact HR to set up benefit plans</p>
              </CardContent>
            </Card>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {myBenefits.map((benefit) => {
                const typeConfig = PLAN_TYPES[benefit.type] || { icon: Heart, color: "bg-slate-100 text-slate-500" };
                const Icon = typeConfig.icon;
                return (
                  <Card key={benefit.id} className={`border-0 shadow-sm ${!benefit.enrolled ? "opacity-60" : ""}`}>
                    <CardContent className="p-5">
                      <div className="flex items-start justify-between mb-3">
                        <div className="flex items-center gap-3">
                          <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${typeConfig.color}`}>
                            <Icon size={20} />
                          </div>
                          <div>
                            <h3 className="text-sm font-semibold text-slate-900">{benefit.name}</h3>
                            <p className="text-xs text-slate-500">{benefit.provider}</p>
                          </div>
                        </div>
                        <Badge variant="outline" className={`text-xs border-0 ${
                          benefit.enrolled ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"
                        }`}>
                          {benefit.enrolled ? (benefit.enrollmentStatus || "Enrolled") : "Not Enrolled"}
                        </Badge>
                      </div>
                      <div className="grid grid-cols-3 gap-3">
                        <div>
                          <p className="text-xs text-slate-500">Monthly Cost</p>
                          <p className="text-sm font-semibold text-slate-900">${benefit.monthlyCost.toLocaleString()}</p>
                        </div>
                        <div>
                          <p className="text-xs text-slate-500">Employer Pays</p>
                          <p className="text-sm font-semibold text-teal-600">${benefit.employerPays.toLocaleString()}</p>
                        </div>
                        <div>
                          <p className="text-xs text-slate-500">You Pay</p>
                          <p className="text-sm font-semibold text-slate-900">${benefit.youPay.toLocaleString()}</p>
                        </div>
                      </div>
                      {!benefit.enrolled && (
                        <Button variant="outline" size="sm" className="mt-3 w-full" onClick={() => toast.info("Enrollment coming soon")}>
                          Enroll Now
                        </Button>
                      )}
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}
        </div>
      )}

      {/* Compensation Tab — Live from compensation records */}
      {activeTab === "compensation" && (
        <div className="space-y-4">
          <Card className="border-0 shadow-sm">
            <CardContent className="p-0">
              <div className="px-5 py-4 border-b border-slate-100">
                <h3 className="font-semibold text-slate-900">Total Compensation Breakdown</h3>
              </div>
              <div className="divide-y divide-slate-100">
                <div className="px-5 py-3 flex items-center justify-between hover:bg-slate-50/50 transition-colors">
                  <div>
                    <p className="text-sm font-medium text-slate-900">Base Salary</p>
                    <p className="text-xs text-slate-500">Annual</p>
                  </div>
                  <p className="text-sm font-bold text-slate-900">${salary.toLocaleString()}</p>
                </div>
                <div className="px-5 py-3 flex items-center justify-between hover:bg-slate-50/50 transition-colors">
                  <div>
                    <p className="text-sm font-medium text-slate-900">Bonuses</p>
                    <p className="text-xs text-slate-500">{myCompRecords.filter((c: any) => c.type === "bonus").length} record(s)</p>
                  </div>
                  <p className="text-sm font-bold text-emerald-600">${bonusTotal.toLocaleString()}</p>
                </div>
                <div className="px-5 py-3 flex items-center justify-between hover:bg-slate-50/50 transition-colors">
                  <div>
                    <p className="text-sm font-medium text-slate-900">Equity</p>
                    <p className="text-xs text-slate-500">{myCompRecords.filter((c: any) => c.type === "equity").length} grant(s)</p>
                  </div>
                  <p className="text-sm font-bold text-violet-600">${equityTotal.toLocaleString()}</p>
                </div>
                <div className="px-5 py-3 flex items-center justify-between hover:bg-slate-50/50 transition-colors">
                  <div>
                    <p className="text-sm font-medium text-slate-900">Benefits Value</p>
                    <p className="text-xs text-slate-500">Employer contribution (annual)</p>
                  </div>
                  <p className="text-sm font-bold text-rose-600">${benefitsValue.toLocaleString()}</p>
                </div>
                <div className="px-5 py-4 bg-slate-50 flex items-center justify-between">
                  <p className="text-sm font-bold text-slate-900">Total Compensation</p>
                  <p className="text-lg font-bold text-teal-600">${totalComp.toLocaleString()}</p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Compensation History from records */}
          <Card className="border-0 shadow-sm">
            <CardContent className="p-5">
              <h3 className="font-semibold text-slate-900 mb-3">Compensation History</h3>
              {myCompRecords.length === 0 ? (
                <div className="py-8 text-center text-slate-400">
                  <TrendingUp size={32} className="mx-auto mb-2 text-slate-300" />
                  <p className="text-sm">No compensation records yet</p>
                  <p className="text-xs mt-1">Raises, bonuses, and equity grants will appear here</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {myCompRecords.map((rec: any) => (
                    <div key={rec.id} className="flex items-center gap-3 p-3 bg-slate-50 rounded-lg">
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${
                        rec.type === "bonus" ? "bg-emerald-100" :
                        rec.type === "equity" ? "bg-violet-100" :
                        rec.type === "raise" ? "bg-blue-100" :
                        "bg-teal-100"
                      }`}>
                        <TrendingUp size={14} className={
                          rec.type === "bonus" ? "text-emerald-600" :
                          rec.type === "equity" ? "text-violet-600" :
                          rec.type === "raise" ? "text-blue-600" :
                          "text-teal-600"
                        } />
                      </div>
                      <div className="flex-1">
                        <p className="text-sm font-medium text-slate-900 capitalize">{rec.type}{rec.notes ? `: ${rec.notes}` : ""}</p>
                        <p className="text-xs text-slate-500">
                          {rec.effectiveDate ? new Date(rec.effectiveDate).toLocaleDateString("en-US", { month: "short", year: "numeric" }) : "—"}
                        </p>
                      </div>
                      <div className="text-right">
                        <p className="text-sm font-bold text-slate-900">${(Number(rec.amount) || 0).toLocaleString()}</p>
                        <Badge variant="outline" className="text-[10px] border-0 bg-slate-100 text-slate-500 capitalize">{rec.type}</Badge>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  );
}
